export default {
  acuteHearing: 'Acute Hearing',
  aethyricAttunement: 'Aethyric Attunement',
  alleyCat: 'Alley Cat',
  ambidextrous: 'Ambidextrous',
  arcaneLore: 'Arcane Lore',
  armouredCasting: 'Armoured Casting',
  artistic: 'Artistic',
  contorsionist: 'Contorsionist',
  coolheaded: 'Coolheaded',
  darkLore: 'Dark Lore',
  darkMagic: 'Dark Magic',
  dealmaker: 'Dealmaker',
  disarm: 'Disarm',
  divineLore: 'Divine Lore',
  dwarfcraft: 'Dwarfcraft',
  etiquette: 'Etiquette',
  excellentVision: 'Excellent Vision',
  fastHands: 'Fast Hands',
  fearless: 'Fearless',
  flee: 'Flee!',
  fleetFooted: 'Fleet Footed',
  flier: 'Flier',
  frenzy: 'Frenzy',
  frightening: 'Frightening',
  grudgeBornFury: 'GrudgeBorn Fury',
  hardy: 'Hardy',
  hedgeMagic: 'Hedge Magic',
  hoverer: 'Hoverer',
  keenSenses: 'Keen Senses',
  lesserMagic: 'Lesser Magic',
  lightningParry: 'Lightning Parry',
  lightningReflexes: 'Lightning Reflexes',
  linguistics: 'Linguistics',
  luck: 'Luck',
  marksman: 'Marksman',
  masterGunner: 'Master Gunner',
  masterOrator: 'Master Orator',
  meditation: 'Meditation',
  menacing: 'Menacing',
  mightyMissile: 'Mighty Missile',
  mightyShot: 'Mighty Shot',
  mimic: 'Mimic',
  naturalWeapons: 'Natural Weapons',
  nightVision: 'Night vision',
  orientation: 'Orientation',
  pettyMagic: 'Petty Magic',
  publicSpeaking: 'Public Speaking',
  quickDraw: 'Quick Draw',
  rapidReload: 'Rapid Reload',
  resistanceToChaos: 'Resistance To Chaos',
  resistanceToDisease: 'Resistance To Disease',
  resistanceToMagic: 'Resistance To Magic',
  resistanceToPoison: 'Resistance To Poison',
  rover: 'Rover',
  savvy: 'Savvy',
  schemer: 'Schemer',
  seasonedTraveller: 'Seasoned Traveller',
  sharpshooter: 'Sharpshooter',
  sixthSense: 'Sixth sense',
  specialistWeaponGroup: 'Specialist Weapon Group',
  stoutHearted: 'StoutHearted',
  streetFighting: 'Street Fighting',
  streetwise: 'Streetwise',
  strikeMightyBlow: 'Strike Mighty Blow',
  strikeToInjure: 'Strike To Injure',
  strikeToStun: 'Strike To Stun',
  strongMinded: 'StrongMinded',
  sturded: 'Sturded',
  suave: 'Suave',
  sureShot: 'Sure Shot',
  surgery: 'Surgery',
  superNumerate: 'Super Numerate',
  swasbuckler: 'Swasbuckler',
  terrifying: 'Terrifying',
  trapfinder: 'Trapfinder',
  trickRiding: 'Trick Riding',
  tunnelRAt: 'Tunnel RAt',
  undead: 'Undead',
  unsettling: 'Unsettling',
  veryResilient: 'Very Resilient',
  veryStrong: 'Very Strong',
  warriorBorn: 'Warrior Born',
  wrestling: 'Wrestling'
}
